name: Hello World

on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        echo Hello World
  
